### ISSUE TITLE
February '14 Meetup #2

### ISSUE THREAD

**Issue by derek** [beerjs/sf#11]
![let's drink](https://pbs.twimg.com/profile_images/1617332644/logo_twitter.png)

**When**: Tuesday, February 18th, 2014 @ 8PM

**Where**:  34 Mason St, San Francisco, CA 94102 ([Map](https://goo.gl/maps/BpfZu))

**RSVP**: No need, but if you reeeeeeeally want to, [meetup.com/beerjs/](http://www.meetup.com/beerjs/).

**How to find us?**: We're typically easy to spot.  But if you really can't find us, pull out your phone, open up [this image](https://raw.github.com/voodootikigod/logo.js/master/beerjs/beerjs.png) in your browser, hold your phone above your head, circle around 3 times, and we'll find you!

**Comment by derek** [comment]
Just got here.  And now begins the game of Spot the Other Nerds!

**Comment by derek** [comment]
Look for the 4 guys in hoodies, and one of them with the JS logo.

**Comment by junosuarez** [comment]
Transcontinental shoutout from Chattanooga - we're organizing our first [BeerJS Chattanooga](https://github.com/beerjs/nooga/issues/2) next Tuesday :)
