### ISSUE TITLE
July '13 Meetup - July 9th, 2013

### ISSUE THREAD

**Issue by derek** [beerjs/sf#2]
**When**: Tuesday, July 9, 2013 @ 8:00 PM
**Where**: Thee Parkside (1600 17th Street)

Moving to the 2nd Tuesday this month due to the holiday.  Also, Thee Parkside worked out well for a meetup in May, so we'll give it another go to switch things up a bit.  Doesn't look like there are any concerts currently scheduled, but I'll keep my eyes open for any that pop up and adjust accordingly.

Worth noting that Change.org (just a few blocks away) is hosting a talk "The Mechanics of Magic: 7 Game Design Insights" at 7pm ([Details and RSVP](http://www.eventbrite.com/event/6955986543/eorg)).

P.S. Mad Caddies fans, they're playing at Bottom of the Hill (also a few blocks away) that night. In! ([tickets](http://www.stubmatic.com/bottomofthehill/event/7810))

---

(original post)

Following the "First Tuesday of Every Month" rule, that would put this next meetup on July 2nd, but due to the proximity to the 4th, I'm wondering if we should schedule for another day?  Also, maybe a different venue to get out and explore some new bars.  Any suggestions?

**Comment by samshull** [comment]
+1 for different venues. I'm still new to SF, so I don't have any suggestions, but I have liked discovering the different bars. I am indifferent about the July 2nd date though.

**Comment by junosuarez** [comment]
Venue-wise, I know you all love the Mission, but it would be easier for me to attend something closer to Caltrain in SoMa.

**Comment by derek** [comment]
FWIW, the reason I picked Bender's last year was simply because that's where JS Pub Nights used to be.  I've spent too little time in SOMA to offer up any suggestions aside from Thirsty Bear, but it seems like a logical neighborhood to have some events due to proximity to all the startups.  We've had 3 or 4 Beer.js events at Thirsty Bear, which have been good, but also crowded and chaotic since it's more of a restaurant as opposed to a dive bar.  

Last week's meetup at Thee Parkside was nice, which is on the outskirts of SOMA.  We'll probably do some events there following any [Change.org talks](http://making.change.org/).  Perhaps we'll just schedule the July meetup at Thee Parkside following the [“The Mechanics of Magic: 7 Game Design Insights”](http://www.eventbrite.com/event/6955986543/eorg) talk on Tuesday, July 9th.

**Comment by derek** [comment]
Posted the info for the [July event](http://www.meetup.com/beerjs/events/123110862/) on Meetup (July 9th @ Thee Parkside).  Sound good?  If so, I'll announce later this week.

**Comment by dshaw** [comment]
My hood!

**Comment by dshaw** [comment]
Though I have to admit that I've never been to Three Parkside. My kids go to their after school program at the park across the street. That's almost the same thing, right?

**Comment by derek** [comment]
Thee Parkside is legit.  Large indoor area (they have concerts there), decent beer selection, greasy bar food, and a cool outdoor patio as well.

![thee parkside](http://ww1.hdnux.com/photos/12/20/64/2690356/6/628x471.jpg)

**Comment by gvt** [comment]
+1 Thee Parkside

**Comment by derek** [comment]
[Announced on meetup.com](http://www.meetup.com/beerjs/events/123110862/)

**Comment by junosuarez** [comment]
@derek The title of this thread is confusing - I just had a conversation with someone at Nodeconf, and we weren't sure if the meetup was on the 9th or the 13th - maybe write out a long date? :)

**Comment by intuedge** [comment]
Note the [']13 in "July '13" referring to July 2013.  The July 2013 meeting
happens on July 9 (2013).

**Comment by derek** [comment]
Good call.  Updated.

**Comment by derek** [comment]
Gameday bump!

**Comment by dshaw** [comment]
:baseball: woot!

**Comment by junosuarez** [comment]
ah, wish I were feeling up to it :( gotta get over this mysterious sickness.

+1 to locations that are accessible by caltrain in the future, though!

**Comment by derek** [comment]
Just got here.  Red jacket.

**Comment by derek** [comment]
Patio is too packed, so we're all hanging out in the front room for the time being

**Comment by derek** [comment]
Fun night!  Thanks for coming out.
