### ISSUE TITLE
Mikkeller's as possible venue

### ISSUE THREAD

**Issue by lakenen** [beerjs/sf#9]
May I suggest a different venue for next month's beerjs? Mikkeller's is a pretty awesome place with terrific beer and a nice downstairs area that is relatively quiet. Bender's is good, but is very dark and loud, which does not facilitate conversation very well. Also, it's nice to mix it up every once in a while!

**Comment by terinjokes** [comment]
+1

**Comment by samshull** [comment]
+1

**Comment by smithclay** [comment]
:metal:

**Comment by derek** [comment]
+1.  Definitely in favor of mixing it up.  I've never been there and curious how it would work for a group our size (30+), so we could try a beer.min.js some random night.  How about Thursday the 23rd?

**Comment by lakenen** [comment]
Their downstairs room could hold a good 20-something people probably (at least). Could also spill upstairs, but the lower level is nicer for conversations IMO. I believe it opens at 6pm most days.

**Comment by terinjokes** [comment]
At least from my POV, we already split into two-ish groups at Benders, so overflowing isn't terrible. I agree with @lakenen, Mikkeller's is much better for conversation.

**Comment by derek** [comment]
Good tip.  Thanks.  If it opens at 6pm, maybe we could bump up the start time a bit before it fills up (if capacity/noise is an issue there).  In any case, I'll check it out in person this week.

**Comment by terinjokes** [comment]
I'm not going to reject a beer.min.js if you want to meet up sometime this week.

**Comment by samshull** [comment]
Yes, do a beer.min.js on the 23rd and I'll join you. It's right around the corner from Zendesk.

**Comment by twolfson** [comment]
Is the beer.min.js officially on? It sounded like speculatively yes but I would like a definitive yes/no.

**Comment by derek** [comment]
Definitely on.  I'll post the event tomorrow.  Short notice, but
considering the name...

**Comment by derek** [comment]
Announced, http://www.meetup.com/beerjs/events/161954312/.

**Comment by lakenen** [comment]
:+1:

**Comment by terinjokes** [comment]
:thumbsup:

**Comment by charliepark** [comment]
Should we head to the downstairs level? Or just look for folks on the main level?

**Comment by lakenen** [comment]
A couple of us are downstairs. There is some kind of company party going on
so it's more crowded than I expected :(

**Comment by lakenen** [comment]
We moved upstairs, if anyone is here...

**Comment by derek** [comment]
Be there in 10min

**Comment by terinjokes** [comment]
@derek: what was your feedback on this for possible implementation in March?

**Comment by derek** [comment]
Definitely doing Mikkeller's for March.  Seemed like a great place once the happy hour work crowd disappeared.

**Comment by derek** [comment]
Experimenting with Beer.js twice a month instead of just once, so the first Tuesday will continue to be at Bender's, and the 3rd Tuesday will be at Mikkeller's.  Next one is Feb 18th.  http://www.meetup.com/beerjs/events/164972372/
